let car = 'subaru';
let num = 101;
let str = '101';
let emptyArr = [];
let numArr = [20, 30, 40];
console.log('test 1');
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log('test 2');
console.log("Is car == 'car'? I predict False.");
console.log(car == 'car');
console.log('test 3');
console.log("Is str == '101'? I predict True");
console.log(str == '101');
console.log('test 4');
console.log("Is str == '100'? I predict False");
console.log(str == '100');
console.log('test 5');
console.log("Is num == 101? I predict True");
console.log(num == 101);
console.log('test 6');
console.log("Is num == 99? I predict False");
console.log(num == 99);
console.log('test 7');
console.log("Is emptyArr.length == 0? I predict True");
console.log(emptyArr.length == 0);
console.log('test 8');
console.log("Is numArr.length == 0? I predict False");
console.log(numArr.length == 0);
console.log('test 9');
console.log("Is numArr.length == 3? I predict True");
console.log(numArr.length == 3);
console.log('test 10');
console.log("Is numArr === emptyArr? I predict False");
console.log(numArr == emptyArr);
export {};
