let num1 = 10;
let num2 = 20;
let str = "HELLO";
console.log("Test 1");
console.log("num1 !== num2");
console.log(num1 !== num2);
console.log("Test 2");
console.log("num1 !== 10");
console.log(num1 !== 10);
console.log("Test 3");
console.log("num2 === 20");
console.log(num2 === 20);
console.log("Test 4");
console.log("num1 === num2");
console.log(num1 === num2);
console.log("Test 5");
console.log("str.toLowerCase() === hello");
console.log(str.toLowerCase() === "hello");
console.log("Test 6");
console.log("str.toLowerCase() === Hello");
console.log(str.toLowerCase() === "Hello");
console.log("Test 7");
console.log("num1 < num2");
console.log(num1 < num2);
console.log("Test 8");
console.log("num2 < num1");
console.log(num2 < num1);
console.log("Test 9");
console.log("num2 > num1");
console.log(num2 > num1);
console.log("Test 10");
console.log("num1 > num2");
console.log(num1 > num2);
console.log("Test 11");
console.log("num1 <= 10");
console.log(num1 <= 10);
console.log("Test 12");
console.log("num1 <= num2");
console.log(num1 <= num2);
console.log("Test 13");
console.log("num1 >= num2");
console.log(num1 >= num2);
console.log("Test 14");
console.log("num2 >= num1");
console.log(num2 >= num1);
console.log("Test 15");
console.log("(num1 < num2)&&(num1 == 10)");
console.log((num1 < num2) && (num1 == 10));
console.log("Test 16");
console.log("(num1 < num2)&&(num1 == 20)");
console.log((num1 < num2) && (num1 == 20));
console.log("Test 17");
console.log("(num2 > num1)||(num2 == 10)");
console.log((num2 > num1) || (num2 == 10));
console.log("Test 18");
console.log("(num1 > num2)||(num1 == 20)");
console.log((num1 > num2) || (num1 == 20));
let numArray = [11, 22, 33, 44];
console.log("Check If 44 is in [11,22,33,44]");
console.log(numArray.indexOf(44) ? "True" : "False");
console.log("Check If 66 is in [11,22,33,44]");
console.log(numArray.indexOf(66) ? "True" : "False");
export {};
